kded: Fix missing xmllint build error
Summary:
To avoid this build error:
    Error: Could not find xmllint
specify libxslt-native as a dependency.

Reviewers: vkrause

Reviewed By: vkrause

Differential Revision: https://phabricator.kde.org/D14171